@echo off
:: Bypass NRO Generator - Windows 11 OOBE Bypass Script
:: Generated: 2026-01-27 16:29:57
:: GitHub: https://github.com/YourUsername/bypassnro

echo ============================================
echo  Windows 11 OOBE Bypass Script
echo  Generated by Bypass NRO Generator
echo ============================================
echo.

:: Download unattend.xml from GitHub
echo Downloading unattend.xml...
curl -L -o C:\Windows\Panther\unattend.xml "https://raw.githubusercontent.com/YourUsername/bypassnro/refs/heads/main/unattend.xml"

if %errorlevel% neq 0 (
    echo Failed to download unattend.xml. Trying alternative method...
    powershell -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/YourUsername/bypassnro/refs/heads/main/unattend.xml' -OutFile 'C:\Windows\Panther\unattend.xml'"
)

if exist C:\Windows\Panther\unattend.xml (
    echo unattend.xml downloaded successfully!
) else (
    echo ERROR: Failed to download unattend.xml
    pause
    exit /b 1
)

:: Set BypassNRO registry key
echo Setting BypassNRO registry key...
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE" /v BypassNRO /t REG_DWORD /d 1 /f

:: Bypass Windows 11 system requirements
echo Bypassing system requirements...
reg add "HKLM\SYSTEM\Setup\LabConfig" /v BypassTPMCheck /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\Setup\LabConfig" /v BypassRAMCheck /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\Setup\LabConfig" /v BypassSecureBootCheck /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\Setup\LabConfig" /v BypassStorageCheck /t REG_DWORD /d 1 /f
reg add "HKLM\SYSTEM\Setup\LabConfig" /v BypassCPUCheck /t REG_DWORD /d 1 /f

:: Disable telemetry
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f

:: Disable Cortana
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" /v AllowCortana /t REG_DWORD /d 0 /f

:: Disable Consumer Features / Content Delivery Manager
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent" /v DisableWindowsConsumerFeatures /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent" /v DisableSoftLanding /t REG_DWORD /d 1 /f

:: Reboot to apply changes
echo.
echo Setup complete! The system will restart in 5 seconds...
echo Press Ctrl+C to cancel.
timeout /t 5
shutdown /r /t 0
